// Code generated by goctl. DO NOT EDIT.
package types

type ReqAssetByLocationID struct {
	LocationID string `json:"location_id"`
}

type ReqAssetByUserPK struct {
	UserPK string `json:"user_pk"`
}

type RespAssetByLocationID struct {
	Assets []*UTXONftInfo `json:"assets"`
}

type RespAssetByUserPK struct {
	Assets []*UTXONftInfo `json:"assets"`
}

type UTXONftInfo struct {
	UserPk                     string
	AtomicalsID                string `json:"atomicals_id"`
	LocationID                 string `json:"location_id"`
	RealmName                  string `json:"realm_name"`
	SubRealmName               string `json:"subrealm_name"`
	ParentRealmAtomicalsID     string `json:"parent_realm_atomicals_id"`
	ContainerName              string `json:"container_name"`
	Dmitem                     string `json:"dmitem"`
	ParentContainerAtomicalsID string `json:"parent_container_atomicals_id"`
	Nonce                      int64  `json:"nonce"`
	Time                       int64  `json:"time"`
	Bitworkc                   string `json:"bitworkc"`
	Bitworkr                   string `json:"bitworkr"`
}
