// Code generated by goctl. DO NOT EDIT.
package types

type ReqAssetByLocationID struct {
	LocationID string `json:"location_id"`
}

type ReqAssetByUserPK struct {
	UserPK string `json:"user_pk"`
}

type ReqCheckTx struct {
	Txid string `json:"tx_id"`
}

type RespAssetByLocationID struct {
	Assets []*UTXONftInfo `json:"assets"`
}

type RespAssetByUserPK struct {
	NftAssets []*UTXONftInfo `json:"nft_assets"`
	FtAssets []*UTXOFtInfo `json:"ft_assets"`
}

type RespCheckTx struct {
	Operation string `json:"operation"`
	Description string `json:"description"`
	Status string `json:"status"`
}

type UTXONftInfo struct {
	UserPk                     string `json:"user_pk"`
	AtomicalsID                string `json:"atomicals_id"`
	LocationID                 string `json:"location_id"`
	RealmName                  string `json:"realm_name"`
	SubRealmName               string `json:"subrealm_name"`
	ParentRealmAtomicalsID     string `json:"parent_realm_atomicals_id"`
	ContainerName              string `json:"container_name"`
	Dmitem                     string `json:"dmitem"`
	ParentContainerAtomicalsID string `json:"parent_container_atomicals_id"`
	Nonce                      int64  `json:"nonce"`
	Time                       int64  `json:"time"`
	Bitworkc                   string `json:"bitworkc"`
	Bitworkr                   string `json:"bitworkr"`
}

type UTXOFtInfo struct {
	UserPk                     string `json:"user_pk"`
	AtomicalsID                string `json:"atomicals_id"`
	LocationID                 string `json:"location_id"`

	Bitworkc                   string `json:"bitworkc"`
	Bitworkr                   string `json:"bitworkr"`

	// DistributedFt
	MintTicker      string `json:"mint_ticker"`
	Nonce                      int64  `json:"nonce"`
	Time                       int64  `json:"time"`
	MintBitworkVec  string `json:"mint_bitwork_vec"`
	MintBitworkcInc string `json:"mint_bitworkc_inc"`
	MintBitworkrInc string `json:"mint_bitwork_rinc"`
	Amount          int64    `json:"amount"`

	// DirectFt
	Type       string  `json:"type"`
	Subtype    string  `json:"sub_type"`
	TickerName string  `json:"ticker_name"`
	MaxSupply  int64  `json:"max_supply"`
	MintAmount int64  `json:"mint_amount"`
	MintHeight int64  `json:"mint_height"`
	MaxMints   int64  `json:"max_mints"`
}

